build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  # Uncomment to add more architectures
  # armv7: ghcr.io/home-assistant/armv7-base:latest
  # armhf: ghcr.io/home-assistant/armhf-base:latest
  # i386: ghcr.io/home-assistant/i386-base:latest
args: {}
labels: {}
codenotary: {}